# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WU145Tys62srNqcppj_ugEOaYnGm71gi
"""

# !pip install streamlit

# !streamlit --version

import streamlit as st

st.write("hello world")